requires = [
  "numpy>=1.20.0",
  "photutils>=1.0",
  "pymc3-ext>=0.1.0",
  "celerite2>=0.2.0",
  "astropy>=4.2",
  "opencv_python>=4.5",
  "matplotlib>=3.4.0",
  "scipy>=1.6",
  "arviz>=0.11.0",
  "corner==2.2.1",
  "exoplanet>=0.4.5",
  "lightkurve>=2.0.10",
  "pymc3>=3.11",
]

build-backend = "setuptools.build_meta"