requires = [
  "numpy>=1.20",
  "photutils>=1.1",
  "pymc3_ext>=0.1",
  "celerite2>=0.2,"
  "astropy>=4.2",
  "opencv_python>=4.5",
  "matplotlib>=3.4",
  "scipy>=1.6",
  "arviz>=0.11",
  "corner>=2.2",
  "exoplanet>=0.5",
  "lightkurve>=2.0",
  "pymc3>=3.11",
]

build-backend = "setuptools.build_meta"